version: "3.7"

services:
  postgres:
    container_name: postgres-bookstore
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    container_name: bookstore-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9010:9010
volumes:
  postgres_data:
    driver: local
